apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "coturn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coturn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: turn-tcp
              containerPort: 3478
              protocol: TCP
            - name: turn-udp
              containerPort: 3478
              protocol: UDP
            - name: turn-tls
              containerPort: 5349
              protocol: TCP
            {{- range $port := untilStep 49152 49157 1 }}
            - name: "relay-{{ $port }}"
              containerPort: {{ $port }}
              protocol: UDP
            {{- end }}
          volumeMounts:
            - name: turnserver-config
              mountPath: /etc/coturn/turnserver.conf
              subPath: turnserver.conf
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: turnserver-config
          configMap:
            name: {{ include "coturn.fullname" . }}-config
