apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jbcalling-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HoanhHop11/JB_Calling_translation_system.git
    targetRevision: main
    path: infrastructure/helm/jbcalling
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jbcalling
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
